---
title: "9.26.2019"
output: github_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
##
##Attaching package: 'ggridges'
## The following object is masked from 'package:ggplot2':
##
##    scale_discrete_manual
```

# Weather Data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
##
## Create a ggplot, aes= aesthetic mapping we care about, without geompoint() we don't have anything on our graph
## geompoint() at a point at each x/y variable we will put a point
##
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
##
## 
```
# Different aesthetic mapping
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
##
## Another way of making above ggplot

```

## Filtering by specific variable name
```{r}
weather_df %>% filter(name == "Central_Park_NY")
```

# saving plot with a name (plot_weather)
```{r}
plot_weather = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax))

plot_weather + geom_point()
```

Adding color... 

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
##
## Adding color into the different points, each color represents a different name (weather station location)
```

